display:
  default:
    display_options:
      fields:
        state:
          label: Status
          separator: ', '
        label:
          label: Label
        source_language_1:
          separator: ', '
        target_language:
          label: Naar
          separator: ', '
        translator:
          label: Provider
        tags_count:
          label: Labels
        operations:
          label: Bewerkingen
      pager:
        options:
          expose:
            items_per_page_label: 'Items per pagina'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Toepassen
          reset_button_label: 'Opnieuw instellen'
          exposed_sorts_label: 'Sorteren op'
          sort_asc_label: Oplopend
          sort_desc_label: Aflopend
      filters:
        state:
          expose:
            label: Status
        source_language:
          expose:
            label: Brontaal
        target_language:
          expose:
            label: Doeltaal
        translator:
          expose:
            label: Provider
  page_1:
    display_title: Pagina
