display:
  default:
    display_options:
      fields:
        title:
          label: Label
  closed:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  completed:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  eligible:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  my_tasks:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  pending:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  rejected:
    display_options:
      fields:
        title:
          label: Label
      filters:
        title:
          expose:
            label: Label
  unassigned:
    display_options:
      fields:
        title:
          label: Label
