display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'Opnieuw instellen'
          exposed_sorts_label: 'Sorteren op'
          sort_asc_label: Oplopend
          sort_desc_label: Aflopend
      pager:
        options:
          expose:
            items_per_page_label: 'Items per pagina'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        media_bulk_form:
          action_title: Actie
        name:
          separator: ', '
        bundle:
          separator: ', '
        uid:
          separator: ', '
        status:
          label: Status
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Bewerkingen
      filters:
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: Status
        langcode:
          expose:
            label: Taal
  user_page:
    display_title: Gebruiker
