display:
  default:
    display_title: Standaard
    display_options:
      fields:
        media_bulk_form:
          action_title: Actie
        name:
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          separator: ', '
        status:
          label: Status
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Bewerkingen
      pager:
        options:
          tags:
            first: '« Eerste'
            last: 'Laatste »'
          expose:
            items_per_page_label: 'Items per pagina'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'Opnieuw instellen'
          exposed_sorts_label: 'Sorteren op'
          sort_asc_label: Oplopend
          sort_desc_label: Aflopend
      filters:
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: Waar
        langcode:
          expose:
            label: Taal
