progress:
  '#changed': 1750521061
  '#changed_by': '1'
  '#completed_items': 10
  '#items':
    install_and_enable_redirect_module:
      '#completed': 1750472502
      '#uid': '1'
    configure_the_redirect_module:
      '#completed': 1750521061
      '#uid': '1'
    install_and_enable_pathauto_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_metatag_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_xml_sitemap_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_robotstxt_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_easy_breadcrumbs_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_sitemap_module:
      '#completed': 1750472502
      '#uid': '1'
    configure_sitemap_module:
      '#completed': 1750472502
      '#uid': '1'
    install_and_enable_yoast_seo_module:
      '#completed': 1750472502
      '#uid': '1'
