_core:
  default_config_hash: xY2q4fE8WXMFw_miwyklJXbZVjl2sv9AtQtrXEjvw7U
file_directories:
  - sites/default/files/2025-12
  - sites/default/files/2025-11
  - sites/default/files/2025-06
  - sites/default/files/2024-12
ignore_patterns:
  - /wp-login
  - /wp-admin
  - /wp-content
  - /wp-includes
  - /xmlrpc.php
  - /.env
  - /.git
  - /phpmyadmin
  - /administrator
  - /cgi-bin
  - .asp
  - .aspx
  - /.well-known
  - /wordpress
  - .php
  - /fastly/
  - /themes/
  - /Home/PublicWeb/
  - /sites/idaholegalaid.org/
  - .zip
  - .tar
  - .gz
  - .rar
  - .bak
  - .tgz
  - .bz
  - '%252'
  - /backup
  - /old
  - /api/
  - /graphql
  - /swagger
  - mysql
  - /sftp
  - /ftp
  - /vendor
  - /config.
  - pma
  - /db
  - '/search/node?'
  - /search-site/
  - /Data/
  - /library/
  - zlib/
  - lib/deflate
  - /de/
  - /fr/
  - /it/
  - /pt/
  - /ko/
  - /ru/
  - /ar/
  - /login
  - /rss
  - /feed
  - /blog
  - /news
  - /admin/
  - inftrees
  - /actuator
  - /debug
  - /telescope
  - /.idea/
  - /.vscode/
  - /.aws/
  - /.ssh/
  - /modules/
  - /includes/
  - __
  - /_
  - /app
  - /new
  - /LegalCheckup
confidence_thresholds:
  high: 90
  medium: 70
  low: 50
default_status_code: 301
export_directory: 'private://redirect_automation'
min_hit_count: 1
enable_logging: true
