key.provider.ilas_runtime_site_setting:
  type: mapping
  label: 'ILAS runtime site setting key provider settings'
  mapping:
    settings_key:
      type: string
      label: 'Drupal site setting key'
