name: ILAS Employment Application Handler
description: Handles employment application form submissions
type: module
core_version_requirement: ^10 || ^11
package: 'Idaho Legal Aid - Forms & Intake'
dependencies:
  - drupal:file
  - drupal:user
  - drupal:system
